services:
  db:
    build:
      context: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - fieldhash-db:/var/lib/postgresql

  backend:
    build:
      context: backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/master"
      SERVER_PORT: 8080
    depends_on:
      - db


volumes:
  fieldhash-db: